TAGS = {
  "donotwant" => (0..4),
  "excited" => (0..9),
  "holyshit" => (0..0),
  "lol" => (0..6),
  "no" => (0..9),
  "nope" => (0..4),
  "omg" => (0..9),
  "popcorn" => (0..9),
  "slowclap" => (0..0),
  "wink" => (0..1),
  "wtf" => (0..9),
  "yeah" => (0..1),
  "yes" => (0..5),
}
